config/routes.rb
Rails.application.routes.draw do
  
  resources :monsters
  resources :tweets, exlude: [:edit, :update, :destroy]
  root "tweets#index"
  resolve("new_tweet_path") {route_for(:new)}
  resolve("new_monster_path ") {route_for(:new)}
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/monster.rb
class Monster < ApplicationRecord
  validates :name, :birthdate, :phone , presence: true, uniqueness: true
  validate :phone_format
  has_many :tweets, dependent: :destroy
  has_many :monster_followers, dependent: :destroy
  
  def phone_format
    if PhoneValidator.new(phone).valid?
      return
    else
      errors.add(:phone, :invalid)
    end
  end
end

app/models/phone_validator.rb
class PhoneValidator
    include HTTParty
    base_uri "https://phonevalidation.abstractapi.com/v1/"

    def initialize(phone)
        @phone  = phone
    end

    def valid?
        response = self.class.get("/", {
            query: {
                api_key: Rails.application.credentials.abstractapi_api_key,
                phone: @phone
            }
        })
        #response is from argentine and valid format
        response["country_code"] == "AR" && response["valid_format"]
     
    end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :monster
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
 def index
    @monsters = Monster.all.order(:name)
 end

 def show
    @monster = Monster.find(params[:id])
 end
 def new
    @monster = Monster.new
 end
 def create
   @monster = Monster.new(monster_params)
   if @monster.save
      redirect_to @monster, notice: "Se ha creado el Monstruo correctamente!"
   else
      render :new
   end
 end
 def edit
      @monster = Monster.find(params[:id])
  end
 def update
   @monster = Monster.find(params[:id])
   if @monster.update(monster_params)
      redirect_to @monster, notice: "Se ha actualizado el Monstruo correctamente!"
   else
      render :edit
   end
 end
 private
 def monster_params
   params.require(:monster).permit(:name, :description, :phone, :birthdate)
 end
 def destroy
   @monster = Monster.find(params[:id])
   @monster.destroy
   redirect_to monsters_path, notice: "Se ha eliminado el Monstruo correctamente!"
 end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
        @tweets = Tweet.all.order(:created_at)
    end
    
    def show
        @tweet = Tweet.find(params[:id])
    end
   
    def new
      @tweet = Tweet.new
    end

    def create
        @tweet = Tweet.new(tweet_params)
        if @tweet.save
            redirect_to @tweet, notice: "Se ha creado el Tweet correctamente!"
        else
            render :new
        end
    end
    private
    def tweet_params
      params.require(:tweet).permit(:content, :monster_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    
end

app/views/application/_left_sidebar.html.erb
<div class="py-2">
  <%= link_to root_path, class: "d-flex align-items-center text-decoration-none mb-4" do %>
    <%= image_tag "superyeti.png", width: 75, class: "bg-secondary rounded-circle", title: "Critter" %>
  <% end %>

  <div class="d-flex flex-column justify-content-end h-100">
    <%= link_to "Inicio", root_path, class: "btn btn-light rounded-pill mb-2 text-start ps-4" %>
    <%= link_to "Monstruos", monsters_path, class: "btn btn-light rounded-pill mb-2 text-start ps-4" %>
    <%= link_to "Twittear", new_tweet_path, class: "btn btn-primary rounded-pill mb-2 text-start ps-4" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-sm-3">
          <%= render "application/left_sidebar" %>
        </div>
        <div class="col-sm-5 border border-top-0">
          <%= yield %>
        </div>
        <div class="col-sm-4"></div>
      </div>
    </div>
  </body>
</html>

app/views/monsters/_form.html.erb
<%= simple_form_for @monster do |m|%>
    <%= m.error_notification %>
    <%= m.input :name, placeholder: "Nombre del Monstruo", class: "form-control mb-2" %>
    <%= m.input :description, class: "form-control mb-2" %>
    <%= m.input :phone , placeholder: "Numero de Telefono", class: "form-control mb-2" %>
    <%= m.input :birthdate %>
    <%= m.submit "Guardar", class: "btn btn-primary mb-2" %>
<%end%>

app/views/monsters/_formedit.html.erb
<%= simple_form_for @monster do |m| %>
  <%= m.error_notification %>
  <%= m.input :name, label: "Nombre", placeholder: "Nombre del Monstruo", class: "form-control mb-2" %>
  <%= m.input :description, label: "Descripción", placeholder: "Descripción del Monstruo", class: "form-control mb-2" %>
  <%= m.input :phone, label: "Telefono", placeholder: "Numero de Telefono", class: "form-control mb-2"%>
  <%= m.input :birthdate, label: "Fecha de Nacimiento", placeholder: "Fecha de Nacimiento", class: "form-control mb-2"%>
  <%= m.submit "Actualizar", class: "btn btn-primary mb-2" %>
<%end%>  

app/views/monsters/edit.html.erb
<h2 class="py-2 mb-0">Editar Monstruo</h2>

<%= render "formedit" , monster: @monster %>

app/views/monsters/index.html.erb
<h1>Listing monsters</h1>

<%= link_to "Crear Monstruo", new_monster_path ,class: "btn btn-primary rounded-pill mb-2 text-start ps-4" %>
<ul>
    <% @monsters.each do |monster| %>
        <li>Mounstro: <%= link_to monster.name, monster %>
        <% if monster.tweets.count > 0 %>
            <span style= "color:red">Twittero destacado</span>
            <% end %>
            <span><%= button_to "Destruir", monster, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %> </span>
        </li>
    <% end %>
</ul>

app/views/monsters/new.html.erb
<h2 class="py-2 mb-0">Nuevo Monstruo</h2>

<%= render "form" , monster: @monster %>

app/views/monsters/show.html.erb
<h1><%= @monster.name %></h1>
<p> <%= @monster.description %></p>
<%= link_to "Editar", edit_monster_path(@monster), class: "btn btn-outline-primary" %> 

app/views/tweets/_form.html.erb
<%= form_with model: tweet do |f| %>
  <%= f.collection_select :monster_id, Monster.order(:name), :id, :name, {}, { class: "form-select mb-2" } %>
  <%= f.text_area :content, placeholder: "¿Qué está pasando?", class: "form-control mb-2" %>

  <%= f.submit "Twittear", class: "btn btn-primary mb-2" %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="row border-top py-3 px-3">
  <div class="col-sm-2 gx-0 text-end">
    <%# https://xsgames.co/randomusers/ %>
    <%= image_tag "https://xsgames.co/randomusers/avatar.php?g=pixel&id=#{SecureRandom.uuid}", class: "img-thumbnail rounded-circle", style: "max-width: 48px" %>
  </div>

  <div class="col-sm-10">
    <p class="mb-0">
      <%= link_to tweet.monster, class: "text-dark text-decoration-none" do %>
        <span class="fw-bold">
          <%= tweet.monster.name %>
        </span>

        <span class="text-secondary">
          <%# This is to simulate a twitter handle %>
          @<%= tweet.monster.name.underscore %>
        </span>
      <% end %>
      ·
      <span class="text-secondary">
        <%# https://guides.rubyonrails.org/action_view_helpers.html#time-ago-in-words %>
        <%= time_ago_in_words(tweet.created_at) %>
      </span>
    </p>

    <%= link_to tweet, class: "text-dark text-decoration-none" do %>
      <p class="mb-0"><%= tweet.content %></p>
    <% end %>
  </div>
</div>

app/views/tweets/index.html.erb
<h2 class="py-2 mb-0">Inicio</h2>

<% @tweets.each do |tweet| %>
  <%= render tweet %>
<% end %>

app/views/tweets/new.html.erb
<h2 class="py-2 mb-0">Nuevo Tweet</h2>

<%= render "form", tweet: @tweet %>

app/views/tweets/show.html.erb
<h2 class="py-2 mb-0">Tweet</h2>

<%= render @tweet %>